# https://github.com/ryanking13/twitter-lyric-bot/blob/master/.github/workflows/tweet.yml
name: crawl

on:
  schedule:
  - cron: "*/15 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
    - name: Crawl
      env:
        BOT_ID: ${{ secrets.BOT_ID }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        GIST_ID: ${{ secrets.GIST_ID }}
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
      run: |
                python app.py
